// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_amenities");

                    b.ToTable("amenities", (string)null);
                });

            modelBuilder.Entity("api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmenitiesCost")
                        .HasColumnType("numeric")
                        .HasColumnName("amenities_cost");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_date");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("HallBaseCost")
                        .HasColumnType("numeric")
                        .HasColumnName("hall_base_cost");

                    b.Property<decimal>("HallDiscountedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("hall_discounted_cost");

                    b.Property<int>("HallId")
                        .HasColumnType("integer")
                        .HasColumnName("hall_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric")
                        .HasColumnName("total_cost");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("HallId")
                        .HasDatabaseName("ix_bookings_hall_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("api.Models.BookingAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer")
                        .HasColumnName("amenity_id");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("numeric")
                        .HasColumnName("price_at_booking");

                    b.HasKey("Id")
                        .HasName("pk_booking_amenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("ix_booking_amenities_amenity_id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_amenities_booking_id");

                    b.ToTable("booking_amenities", (string)null);
                });

            modelBuilder.Entity("api.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("CostPerHour")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_per_hour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_halls");

                    b.ToTable("halls", (string)null);
                });

            modelBuilder.Entity("api.Models.HallAmenity", b =>
                {
                    b.Property<int>("HallId")
                        .HasColumnType("integer")
                        .HasColumnName("hall_id");

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer")
                        .HasColumnName("amenity_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("HallId", "AmenityId")
                        .HasName("pk_hall_amenities");

                    b.HasIndex("AmenityId")
                        .HasDatabaseName("ix_hall_amenities_amenity_id");

                    b.ToTable("hall_amenities", (string)null);
                });

            modelBuilder.Entity("api.Models.Booking", b =>
                {
                    b.HasOne("api.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_halls_hall_id");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("api.Models.BookingAmenity", b =>
                {
                    b.HasOne("api.Models.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_amenities_amenities_amenity_id");

                    b.HasOne("api.Models.Booking", "Booking")
                        .WithMany("BookedAmenities")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_amenities_bookings_booking_id");

                    b.Navigation("Amenity");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("api.Models.HallAmenity", b =>
                {
                    b.HasOne("api.Models.Amenity", "Amenity")
                        .WithMany("HallAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_amenities_amenities_amenity_id");

                    b.HasOne("api.Models.Hall", "Hall")
                        .WithMany("HallAmenities")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hall_amenities_halls_hall_id");

                    b.Navigation("Amenity");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("api.Models.Amenity", b =>
                {
                    b.Navigation("HallAmenities");
                });

            modelBuilder.Entity("api.Models.Booking", b =>
                {
                    b.Navigation("BookedAmenities");
                });

            modelBuilder.Entity("api.Models.Hall", b =>
                {
                    b.Navigation("HallAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
